title: "伸び悩んでいる3年目Webエンジニアのための、Python Webアプリケーション自作入門"
summary: |
  ///////////////////////////////////////////////////////////////////////////////////
  // この書籍は現在執筆中です。
  // 皆様のフィードバックで執筆速度が変わります。
  // 続きを読みたい方は、是非いいねや筆者フォローをお願いします。
  ///////////////////////////////////////////////////////////////////////////////////\n

  本書は、Webフレームワークを使ってお作法に則ってWebサービスを作ることができるようになってきたはいいものの、周囲の先輩エンジニアほど自分のサービスを深く理解できているわけではなく、かといって業務では同じような作業の繰り返しで学びが深まっている気がせず、スキルが頭打ちになっているのではないかと悩む、3年目Webエンジニアに捧げる本です。

  Webアプリケーション（＝ブラウザからアクセス可能で、動的なHTMLを返すことができるHTTPサーバー）をフレームワークを極力使わずに自作することで、フレームワークやWebサーバーの動作を深く理解し、より高度なWebサービス開発ができるようになることをゴールとしています。
  なお、言語はPythonを使用します。

  執筆中は全編無料で公開予定です。

  ========== サポートとソースコードはこちらから ==========
  https://github.com/bigen1925/python_web_application_for_3rd_year_engineer

  ========== 更新履歴はこちら ==========
  TBW

topics: ["python", "web", "socket", "http", "tcp"] # トピック（5つまで）
published: false
price: 0
chapters:
  - preface.md