title: "伸び悩んでいる3年目Webエンジニアのための、Python Webアプリケーション自作入門"
summary: |
  ///////////
  // 本書は現在執筆中です。
  // 掲載中のソースコードや公開済みの文章に
  // 予告なく修正を加えることがあります。
  //
  // また、読者からのフィードバックを心よりお待ちしております。
  // フィードバックが得られない場合執筆を中断することもありますので、
  // 是非ご協力ください。
  //
  // 下記フォームで簡単なアンケートをしていますので、
  // 本書の続きを読みたい方は是非ご回答ください（所要時間1分）。
  // https://docs.google.com/forms/d/1qTTNPbyPyAAMYALth5uDqgsDGmlCe-BXLYYDLk0QKfw/edit?usp=drive_web
  //
  // また、更新の際には毎回記事を投稿していますので、
  // Zennで筆者をフォローしていただけると更新通知が受け取れます。
  //
  // 本書のLike!、twitterやFacebookでの拡散も大歓迎です ;-)
  ///////////

  本書は、Webフレームワークを使ってお作法に則ってWebサービスを作ることができるようになってきたはいいものの、周囲の先輩エンジニアほど自分のサービスを深く理解できているわけではなく、かといって業務では同じような作業の繰り返しで学びが深まっている気がせず、スキルが頭打ちになっているのではないかと悩む、3年目Webエンジニアに捧げる本です。

  Webアプリケーション（＝ブラウザからアクセス可能で、動的なHTMLを返すことができるHTTPサーバー）をフレームワークを極力使わずに自作することで、フレームワークやWebサーバーの動作を深く理解し、より高度なWebサービス開発ができるようになることをゴールとしています。
  なお、言語はPythonを使用します。

  執筆中は全編無料で公開予定です。

  === 本書に関する質問や誤植連絡、ソースコードはこちらから ===
  https://github.com/bigen1925/introduction-to-web-application-with-python

topics: ["python", "web", "socket", "http", "tcp"] # トピック（5つまで）
published: true
price: 0
chapters:
  - preface.md
  - introduction.md
  - what-is-web-application.md
  - making-silly-web-server.md
  - making-silly-web-server-step1.md
  - making-silly-web-server-step2.md
  - making-silly-web-server-step3.md
  - making-silly-web-server-step4.md
  - what-is-http.md
  - improve-to-minimal-web-server.md
  - delivery-static-html.md
  - daemonize.md
  - threading.md
  - dynamic-response-generation.md
  - post-parameters.md
  - response-request-view.md
  - draft4.md
  - draft5.md
  - draft6.md
  - draft7.md
  - draft8.md
  - draft9.md
  - draft10.md
  - draft11.md