title: "伸び悩んでいる3年目Webエンジニアのための、Python Webアプリケーション自作入門"
summary: |
  本書は、Webフレームワークを使ってお作法に則ってWebサービスを作ることができるようになってきたはいいものの、周囲の先輩エンジニアほど自分のサービスを深く理解できているわけではなく、かといって業務では同じような作業の繰り返しで学びが深まっている気がせず、スキルが頭打ちになっているのではないかと悩む、3年目Webエンジニアに捧げる本です。

  Webサーバーをフレームワークやライブラリを極力使わずに自作することでWebアプリケーションの動作を深く理解し、より高度なWebサービス開発ができるようになることをゴールとしています。
  なお、言語はPythonを使用します。

  本書は当面無料で公開する予定ですが、予告なく有料に変更する可能性があります。
  勉強になったという方は、ぜひ無料のうちにTwitterやFacebookなどで友人に紹介してあげてください ;)

  また、本書では今後の情報発信の参考のために読者の皆様のご意見を募集しています
  今後の新しい書籍の執筆や、単発記事の執筆などをご期待されるかたは、是非下記アンケートフォームよりご回答ください。（所要時間1分）
  https://forms.gle/TXsfdPspD91Lmhzu5

  === 本書に関する質問や誤植連絡、ソースコードはこちらから ===
  https://github.com/bigen1925/introduction-to-web-application-with-python

topics: ["python", "web", "socket", "http", "tcp"] # トピック（5つまで）
published: true
price: 0
chapters:
  - preface.md
  - introduction.md
  - what-is-web-application.md
  - making-silly-web-server.md
  - making-silly-web-server-step1.md
  - making-silly-web-server-step2.md
  - making-silly-web-server-step3.md
  - making-silly-web-server-step4.md
  - what-is-http.md
  - improve-to-minimal-web-server.md
  - delivery-static-html.md
  - daemonize.md
  - threading.md
  - dynamic-response-generation.md
  - post-parameters.md
  - response-request-view.md
  - modulize.md
  - url-resolver.md
  - template-engine.md
  - cookie.md
  - epilogue